### ISSUE TITLE
Settings GUI crash on open

### ISSUE THREAD

**Issue by F0x06** [HexoMod/WorldEditCUI-Forge-Edition-2#6]
Hi, when i press the binded key to open the settings GUI my game crashes

Mods installed: WorldEdit CUI Forge Edition 2-2.1.1-mf-1.12-14.21.0.2334 (disabled other mods to test)
Forge version: 14.21.0.2349, same problem on latest 14.21.0.2373
Minecraft version: 1.12

StackTrace:
```
21:44:30	game		info	[19:44:30] [main/ERROR] [FML]: Exception caught during firing event net.minecraftforge.fml.common.gameevent.InputEvent$KeyInputEvent@5fb18396:
21:44:30	game		info	java.lang.NoSuchFieldError: fontRendererObj
21:44:30	game		info	at com.github.hexomod.worldeditcuife2.bb.<init>(TextTooltipImpl.java:22) ~[bb.class:?]
21:44:30	game		info	at com.github.hexomod.worldeditcuife2.q.c(GeneralConfig.java:51) ~[q.class:?]
21:44:30	game		info	at com.github.hexomod.worldeditcuife2.d.<init>(OptionsContainer.java:34) ~[d.class:?]
21:44:30	game		info	at com.github.hexomod.worldeditcuife2.i.<init>(ConfigContainer.java:29) ~[i.class:?]
21:44:30	game		info	at com.github.hexomod.worldeditcuife2.q.<init>(GeneralConfig.java:41) ~[q.class:?]
21:44:30	game		info	at com.github.hexomod.worldeditcuife2.f.c(ScrollContainer.java:57) ~[f.class:?]
21:44:30	game		info	at com.github.hexomod.worldeditcuife2.d.<init>(OptionsContainer.java:34) ~[d.class:?]
21:44:30	game		info	at com.github.hexomod.worldeditcuife2.f.<init>(ScrollContainer.java:47) ~[f.class:?]
21:44:30	game		info	at com.github.hexomod.worldeditcuife2.e.a(OptionsScreen.java:58) ~[e.class:?]
21:44:30	game		info	at com.github.hexomod.worldeditcuife2.T.func_73866_w_(BasicScreen.java:86) ~[T.class:?]
21:44:30	game		info	at net.minecraft.client.gui.GuiScreen.func_146280_a(GuiScreen.java:478) ~[bli.class:?]
21:44:30	game		info	at net.minecraft.client.Minecraft.func_147108_a(Minecraft.java:1016) ~[bhz.class:?]
21:44:30	game		info	at com.github.hexomod.worldeditcuife2.t.a(KeyHandler.java:78) ~[t.class:?]
21:44:30	game		info	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_8_t_a_KeyInputEvent.invoke(.dynamic) ~[?:?]
21:44:30	game		info	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
21:44:30	game		info	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:186) [EventBus.class:?]
21:44:30	game		info	at net.minecraftforge.fml.common.FMLCommonHandler.fireKeyInput(FMLCommonHandler.java:567) [FMLCommonHandler.class:?]
21:44:30	game		info	at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:2011) [bhz.class:?]
21:44:30	game		info	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1801) [bhz.class:?]
21:44:30	game		info	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1096) [bhz.class:?]
21:44:30	game		info	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397) [bhz.class:?]
21:44:30	game		info	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
21:44:30	game		info	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
21:44:30	game		info	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_25]
21:44:30	game		info	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_25]
21:44:30	game		info	at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_25]
21:44:30	game		info	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
21:44:30	game		info	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
21:44:30	game		info	[19:44:30] [main/ERROR] [FML]: Index: 1 Listeners:
21:44:30	game		info	[19:44:30] [main/ERROR] [FML]: 0: NORMAL
21:44:30	game		info	[19:44:30] [main/ERROR] [FML]: 1: ASM: com.github.hexomod.worldeditcuife2.t@5c16f550 a(Lnet/minecraftforge/fml/common/gameevent/InputEvent$KeyInputEvent;)V
21:44:31	game		info	[19:44:31] [Server thread/INFO]: Stopping server
21:44:31	game		info	[19:44:31] [Server thread/INFO]: Saving players
21:44:31	game		info	[19:44:31] [Server thread/INFO]: Saving worlds
21:44:31	game		info	[19:44:31] [Server thread/INFO]: Saving chunks for level 'Copy of New World'/overworld
21:44:31	game		info	[19:44:31] [Server thread/INFO]: Saving chunks for level 'Copy of New World'/the_nether
21:44:31	game		info	[19:44:31] [Server thread/INFO]: Saving chunks for level 'Copy of New World'/the_end
21:44:31	game		info	[19:44:31] [Server thread/INFO] [FML]: Unloading dimension 0
21:44:31	game		info	[19:44:31] [Server thread/INFO] [FML]: Unloading dimension -1
21:44:31	game		info	[19:44:31] [Server thread/INFO] [FML]: Unloading dimension 1
21:44:31	game		info	[19:44:31] [Server thread/INFO] [FML]: Applying holder lookups
21:44:31	game		info	[19:44:31] [Server thread/INFO] [FML]: Holder lookups applied
21:44:32	game		info	[19:44:32] [main/FATAL]: Unreported exception thrown!
21:44:32	game		info	java.lang.NoSuchFieldError: fontRendererObj
21:44:32	game		info	at com.github.hexomod.worldeditcuife2.bb.<init>(TextTooltipImpl.java:22) ~[bb.class:?]
21:44:32	game		info	at com.github.hexomod.worldeditcuife2.q.c(GeneralConfig.java:51) ~[q.class:?]
21:44:32	game		info	at com.github.hexomod.worldeditcuife2.d.<init>(OptionsContainer.java:34) ~[d.class:?]
21:44:32	game		info	at com.github.hexomod.worldeditcuife2.i.<init>(ConfigContainer.java:29) ~[i.class:?]
21:44:32	game		info	at com.github.hexomod.worldeditcuife2.q.<init>(GeneralConfig.java:41) ~[q.class:?]
21:44:32	game		info	at com.github.hexomod.worldeditcuife2.f.c(ScrollContainer.java:57) ~[f.class:?]
21:44:32	game		info	at com.github.hexomod.worldeditcuife2.d.<init>(OptionsContainer.java:34) ~[d.class:?]
21:44:32	game		info	at com.github.hexomod.worldeditcuife2.f.<init>(ScrollContainer.java:47) ~[f.class:?]
21:44:32	game		info	at com.github.hexomod.worldeditcuife2.e.a(OptionsScreen.java:58) ~[e.class:?]
21:44:32	game		info	at com.github.hexomod.worldeditcuife2.T.func_73866_w_(BasicScreen.java:86) ~[T.class:?]
21:44:32	game		info	at net.minecraft.client.gui.GuiScreen.func_146280_a(GuiScreen.java:478) ~[bli.class:?]
21:44:32	game		info	at net.minecraft.client.Minecraft.func_147108_a(Minecraft.java:1016) ~[bhz.class:?]
21:44:32	game		info	at com.github.hexomod.worldeditcuife2.t.a(KeyHandler.java:78) ~[t.class:?]
21:44:32	game		info	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_8_t_a_KeyInputEvent.invoke(.dynamic) ~[?:?]
21:44:32	game		info	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
21:44:32	game		info	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:186) ~[EventBus.class:?]
21:44:32	game		info	at net.minecraftforge.fml.common.FMLCommonHandler.fireKeyInput(FMLCommonHandler.java:567) ~[FMLCommonHandler.class:?]
21:44:32	game		info	at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:2011) ~[bhz.class:?]
21:44:32	game		info	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1801) ~[bhz.class:?]
21:44:32	game		info	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1096) ~[bhz.class:?]
21:44:32	game		info	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397) [bhz.class:?]
21:44:32	game		info	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
21:44:32	game		info	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
21:44:32	game		info	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_25]
21:44:32	game		info	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_25]
21:44:32	game		info	at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_25]
21:44:32	game		info	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
21:44:32	game		info	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
21:44:32	game		info	[19:44:32] [main/INFO] [STDOUT]: [net.minecraft.init.Bootstrap:func_179870_a:552]: ---- Minecraft Crash Report ----
21:44:32	game		info	// I just don't know what went wrong :(
21:44:32	game		info	
21:44:32	game		info	Time: 6/26/17 7:44 PM
21:44:32	game		info	Description: Unexpected error
21:44:32	game		info	
21:44:32	game		info	java.lang.NoSuchFieldError: fontRendererObj
21:44:32	game		info	at com.github.hexomod.worldeditcuife2.bb.<init>(TextTooltipImpl.java:22)
21:44:32	game		info	at com.github.hexomod.worldeditcuife2.q.c(GeneralConfig.java:51)
21:44:32	game		info	at com.github.hexomod.worldeditcuife2.d.<init>(OptionsContainer.java:34)
21:44:32	game		info	at com.github.hexomod.worldeditcuife2.i.<init>(ConfigContainer.java:29)
21:44:32	game		info	at com.github.hexomod.worldeditcuife2.q.<init>(GeneralConfig.java:41)
21:44:32	game		info	at com.github.hexomod.worldeditcuife2.f.c(ScrollContainer.java:57)
21:44:32	game		info	at com.github.hexomod.worldeditcuife2.d.<init>(OptionsContainer.java:34)
21:44:32	game		info	at com.github.hexomod.worldeditcuife2.f.<init>(ScrollContainer.java:47)
21:44:32	game		info	at com.github.hexomod.worldeditcuife2.e.a(OptionsScreen.java:58)
21:44:32	game		info	at com.github.hexomod.worldeditcuife2.T.func_73866_w_(BasicScreen.java:86)
21:44:32	game		info	at net.minecraft.client.gui.GuiScreen.func_146280_a(GuiScreen.java:478)
21:44:32	game		info	at net.minecraft.client.Minecraft.func_147108_a(Minecraft.java:1016)
21:44:32	game		info	at com.github.hexomod.worldeditcuife2.t.a(KeyHandler.java:78)
21:44:32	game		info	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_8_t_a_KeyInputEvent.invoke(.dynamic)
21:44:32	game		info	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
21:44:32	game		info	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:186)
21:44:32	game		info	at net.minecraftforge.fml.common.FMLCommonHandler.fireKeyInput(FMLCommonHandler.java:567)
21:44:32	game		info	at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:2011)
21:44:32	game		info	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1801)
21:44:32	game		info	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1096)
21:44:32	game		info	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
21:44:32	game		info	at net.minecraft.client.main.Main.main(SourceFile:123)
21:44:32	game		info	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
21:44:32	game		info	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
21:44:32	game		info	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
21:44:32	game		info	at java.lang.reflect.Method.invoke(Method.java:483)
21:44:32	game		info	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
21:44:32	game		info	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
21:44:32	game		info	
21:44:32	game		info	
21:44:32	game		info	A detailed walkthrough of the error, its code path and all known details is as follows:
21:44:32	game		info	---------------------------------------------------------------------------------------
21:44:32	game		info	
21:44:32	game		info	-- Head --
21:44:32	game		info	Thread: Client thread
21:44:32	game		info	Stacktrace:
21:44:32	game		info	at com.github.hexomod.worldeditcuife2.bb.<init>(TextTooltipImpl.java:22)
21:44:32	game		info	at com.github.hexomod.worldeditcuife2.q.c(GeneralConfig.java:51)
21:44:32	game		info	at com.github.hexomod.worldeditcuife2.d.<init>(OptionsContainer.java:34)
21:44:32	game		info	at com.github.hexomod.worldeditcuife2.i.<init>(ConfigContainer.java:29)
21:44:32	game		info	at com.github.hexomod.worldeditcuife2.q.<init>(GeneralConfig.java:41)
21:44:32	game		info	at com.github.hexomod.worldeditcuife2.f.c(ScrollContainer.java:57)
21:44:32	game		info	at com.github.hexomod.worldeditcuife2.d.<init>(OptionsContainer.java:34)
21:44:32	game		info	at com.github.hexomod.worldeditcuife2.f.<init>(ScrollContainer.java:47)
21:44:32	game		info	at com.github.hexomod.worldeditcuife2.e.a(OptionsScreen.java:58)
21:44:32	game		info	at com.github.hexomod.worldeditcuife2.T.func_73866_w_(BasicScreen.java:86)
21:44:32	game		info	at net.minecraft.client.gui.GuiScreen.func_146280_a(GuiScreen.java:478)
21:44:32	game		info	at net.minecraft.client.Minecraft.func_147108_a(Minecraft.java:1016)
21:44:32	game		info	at com.github.hexomod.worldeditcuife2.t.a(KeyHandler.java:78)
21:44:32	game		info	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_8_t_a_KeyInputEvent.invoke(.dynamic)
21:44:32	game		info	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
21:44:32	game		info	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:186)
21:44:32	game		info	at net.minecraftforge.fml.common.FMLCommonHandler.fireKeyInput(FMLCommonHandler.java:567)
21:44:32	game		info	at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:2011)
```

**Comment by hexosse** [comment]
I just released a new version [WorldEdit CUI Forge Edition 2-2.1.2-mf-1.12-14.21.0.2373](https://minecraft.curseforge.com/projects/worldeditcui-forge-edition-2/files/2442016) which solve this issue.
